READY='Ready'
PENDING='Pending'
IN_PROGRESS='In Progress'
ESCALATE_LEVEL_1='Escalation - Field Lead'
ESCALATE_LEVEL_2='Escalation - Back Office'
ESCALATE_LEVEL_3='Escalation - Vendor'
NO_COMPLIANT='Non-compliant'
COMPLETED='Completed'
