
###
// login
POST {{server_base_url}}/
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

cmd=login&usr={{username}}&pwd={{password}}&device=desktop

###

// get filter options for job list
GET {{server_base_url}}/api/method/install_manager.install_manager.page.job_management.job_management.get_list_filter_options
        ?escalation_view=true

###

// search active jobs
// all request attributes are optional
POST {{server_base_url}}/api/method/install_manager.install_manager.page.job_management.job_management.list_active_jobs
Content-Type: application/json

{
  "filters": {
    "team_id": "Level I Team 1",
    "statuses": ["In Progress", "Ready"],
    "building_numbers": [1],
    "schedule_ids": ["ASSIGN-00001"]
  }
}
###
