
###
// login
POST {{server_base_url}}/
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

cmd=login&usr={{username}}&pwd={{password}}&device=desktop

###

// get filter options for job list
GET {{server_base_url}}/api/method/install_manager.install_manager.page.job_management.job_management.get_list_filter_options
        ?escalation_view=false

###

// search active jobs
// all request attributes are optional
POST {{server_base_url}}/api/method/install_manager.install_manager.page.job_management.job_management.list_active_jobs
Content-Type: application/json

{
  "filters": {
    "team_id": "",
    "statuses": [],
    "building_numbers": [],
    "schedule_ids": []
  }
}
###

// Load and save detail
//         frappe.model.clear_doc("Job", 'JOB-000001');
        // Load
#        frappe.model
#            .with_doc("Job", 'JOB-000001')
#            .then((result) => {
#                consoleave.log(result);
#                // Save
#                frappe.call({
#                    freeze: true,
#                    method: "frappe.desk.form.save.savedocs",
#                    args: {doc: result, action: "Save"},
#                    callback: function (r) {
#                        console.log(r)
#                    }
#                })
#            });
// Load job detail
GET {{server_base_url}}/api/method/frappe.desk.form.load.getdoc
    ?doctype=Job
    &name=JOB-000001
    &_={{$timestamp}}

###
